### PR TITLE
Updated to ARCore 1.1.

### PR DESCRIPTION
**Pull request by eisenbruch**
Removed outdated ARCore Unity assets and updated to ARCore 1.1. Updated code in ARSurface.cs and ARSurfaceManager.cs to work with ARCore 1.1.

### CODE REVIEW

**Comment by jonas-johansson** [comment]
Fantastic!

I don't have time to look through the changes right now as the SDK 1.1 touched a lot of files. But I'll accept this pull request to let people give it a go. I've been thinking about having the SDK out-of-repo to minimize the changes on upgrade.

High five!

**Comment by eisenbruch** [comment]
Great! Yea, SDK out-of-repo isn't a bad idea.

**Comment by jonas-johansson** [comment]
Right, I'm gonna think about that. It was like that in the beginning but
people had a hard time to get going. Having the demo scene and the SDK is
instant for trying it out. Anyway, gonna think more about it.

**Comment by eisenbruch** [comment]
Ah right, the demo scene. Def needs some thinking.

**Pull request merged**
